In [1]:
heights=[10,20,30]
weights=[51,43,56]

In [3]:
import numpy as np
heights=np.array(heights)
weights=np.array(weights)

In [4]:
bmi=heights*weights

In [5]:
bmi

array([ 510,  860, 1680])

In [6]:
bmi[2]

1680

In [7]:
bmi[:]

array([ 510,  860, 1680])

In [9]:
bmi[-3]

510

In [10]:
bmi[-3:]

array([ 510,  860, 1680])

In [11]:
bmi>1000

array([False, False,  True])

In [12]:
bmi[bmi>1000]

array([1680])

In [13]:
bmi.max()

1680

In [14]:
bmi.min()

510

In [15]:
bmi.mean()

1016.6666666666666