# 3 main benefits of numpy over a python list

1. Less memory
2. Fast
3. Convinient

# Basic array operations

In [1]:
import numpy as np

In [3]:
# create one dimensional array

a=np.array([5,6,9])
a[0]

5

In [5]:
# create 2 dimensional aray

a=np.array([[1,2],[3,4],[5,6]])

In [6]:
a[0]

array([1, 2])

In [7]:
# return the dimension
a.ndim

2

In [8]:
a.itemsize # item size of 1 element

4

In [9]:
#shows the datatype

a.dtype

dtype('int32')

In [10]:
#convert the array type to float

a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)

In [11]:
a.dtype

dtype('float64')

In [12]:
a.size # size of toal number of elements

6

In [13]:
a.shape # 3 rows and 2 columns

(3, 2)

In [15]:
#convert to complex datatype

a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [16]:
np.zeros((3,4)) # creating the array with zero for the dimension given 3 rows,4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
l=range(5)
l[0]

0

In [19]:
np.arange(1,5) # like python range function


array([1, 2, 3, 4])

In [20]:
np.arange(1,5,2) # step of 2

array([1, 3])

In [22]:
#linspace - generate 10 numbers between 1 and 5 - linearly spaced

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [24]:
a=np.array([[1,2],[3,4],[5,6]])

In [25]:
a.shape

(3, 2)

In [26]:
a.reshape(2,3) # reshaping the array based on the dimension given

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
a.ravel() # flatten the array , this function doesn't overwrite the orignial array

array([1, 2, 3, 4, 5, 6])

In [29]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.min()

1

In [31]:
a.max()

6

In [32]:
a.sum()

21

In [33]:
a.sum(axis=0) # vertically

array([ 9, 12])

In [34]:
a.sum(axis=1) # horizontally

array([ 3,  7, 11])

In [38]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [39]:
np.std(a)

1.707825127659933

In [42]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [43]:
a+b

array([[ 6,  8],
       [10, 12]])

In [46]:
a.dot(b) # multiplication

array([[19, 22],
       [43, 50]])

# Slicing

In [47]:
a=np.array([6,7,8]) # similar to python list

In [48]:
a[0:2]

array([6, 7])

In [49]:
a[-1] #last element

8

In [53]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [54]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [55]:
a[1,2] #first row and second element

5

In [56]:
a[0:2,2] # i the 0th and 1st row, picks the last element from both the rows

array([3, 5])

In [57]:
a[-1] #last row

array([5, 6, 7])

In [58]:
a[-1,0:2]

array([5, 6])

In [60]:
a[:,1:3]

array([[2, 3],
       [4, 5],
       [6, 7]])

# Iterate through Arrays

In [61]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])

In [62]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [63]:
for row in a:
    print(row)

[1 2 3]
[3 4 5]
[5 6 7]


In [66]:
for row in a.flat:
    print(row)

1
2
3
3
4
5
5
6
7


# Stacking Arrays

In [70]:
a=np.arange(6)
b=np.arange(6,12)
a
b

array([ 6,  7,  8,  9, 10, 11])

In [69]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
b.reshape(3,2)

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [72]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [74]:
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
c=np.arange(30).reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [79]:
# to split
result=np.hsplit(c,3)

In [80]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [82]:
result=np.vsplit(c,2)
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

# Indexing with Boolean array

In [85]:
d=np.arange(12).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
bool1=d>4
bool1

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
d[bool1] # returns the value from the num array with true condition
# returns the value from the array which are greater than 4

array([ 5,  6,  7,  8,  9, 10, 11])

In [97]:
d[bool1]=-1
d

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# Numpy Nditer

In [124]:
a=np.arange(12).reshape(3,4)

In [125]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
a.ndim

2

In [127]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [128]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [129]:
for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [130]:
for x in np.nditer(a,order='C'): #c order
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [131]:
for x in np.nditer(a,order='F'): #FORTRAN order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [132]:
for x in np.nditer(a,order='F',flags=['external_loop']): #FORTRAN order
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [133]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x


In [134]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [135]:
# iterate 2 arrays at the same time

b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [136]:
for x,y in np.nditer([a,b]):
    print(x,y) # 2 arrays dimension should be compatible

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
